### ISSUE TITLE
Not working correctly on beta 13

### ISSUE THREAD

**Issue by flaiming** [AntoineFr/flarum-ext-online#17]
Seems that this extension is not working corectly on Flarum beta 13. It shows myself as online, but no other members are showing there even if they are definitely online as well.

**Comment by AntoineFr** [comment]
Hello,

I am aware of this issue which is not related to Flarum beta 13, it only shows someone if you visited his profile after you last page reloading.
However I never found an explanation for this, I should maybe get the users in another way but I don't have much time free for this right now :/
I'll definitely try to fix this one day or another.
