### ISSUE TITLE
Update Beta 14?

### ISSUE THREAD

**Issue by joonsushim** [AntoineFr/flarum-ext-online#21]
Hello Antoine, 
I was wondering if you were going to update this extension for Beta 14 ( Really liked the "money" ext as well that got released for Beta 14 :) )
Thanks!

**Comment by AntoineFr** [comment]
Hello,

This extension never really worked (sometimes only showing yourself in the list even if other members are connected).
I could update it for beta 14 but I think there's more work that needs to be done to get it working fully, so I can't do that right now :/

**Comment by joonsushim** [comment]
Hi, I understand :/ .
Thank you for your answer ! :)
