### ISSUE TITLE
Update Beta 16?

### ISSUE THREAD

**Issue by ghost** [AntoineFr/flarum-ext-online#25]
Hello, will the extension be updated to beta 16?

**Comment by Nearata** [comment]
if @AntoineFr or someone else is not already working on this, i'd be more than happy to contribute on it.

**Comment by AntoineFr** [comment]
Hello @Nearata, I haven't started updating this extension for the latest Flarum versions, you can do it if you want!

**Comment by Nearata** [comment]
i'm working on it.
