### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by ghost** [AntoineFr/flarum-ext-online#28]
Hello, the next problem after updating your administration panel can not be entered after this installation because an error pops up like this:

Something went wrong trying to load the full page. Try to delete the browser cache files and enter again.

the cache was reset and still the same.

will be revised and tested by you?

![Zrzut ekranu (182)](https://user-images.githubusercontent.com/57603425/117776764-2eed0800-b23c-11eb-8576-18e67a089664.png)

**Comment by Nearata** [comment]
@pkwiadaro ~are you using the latest release (0.4.0 - beta15) or dev-master?~ 0.4.0 is not beta16 compatible.

**Comment by ghost** [comment]
well, I have beta 16, and when will it be compatible?

**Comment by AntoineFr** [comment]
We updated this extension at the beginning of this week, I will publish a new release at the end of this week.

**Comment by ghost** [comment]
it's cleared up and I'm waiting.
