### ISSUE TITLE
Mobile views enhancement

### ISSUE THREAD

**Issue by BlueWhaleYT** [AntoineFr/flarum-ext-online#31]
It is fabulous when using tablets and desktops to display the online list. However, it doesn’t perform well in responsive view. I would like to suggest altering the vertical list to be a horizontal list which is scrollable for the responsive views.
I tried implementing this using css but it was a hard work for me due to no classes for the ul element.

**Comment by AntoineFr** [comment]
I am currently adding a new feature to this extension: an option to display the online users list at top of the forum.
I just tried it in mobile view and it looks good. What do you think?

![Capture d’écran 2021-05-30 à 11 54 31](https://user-images.githubusercontent.com/4655583/120066034-d6f43500-c074-11eb-8d3a-9c76a23439bf.png)

**Comment by BlueWhaleYT** [comment]
> I am currently adding a new feature to this extension: an option to display the online users list at top of the forum.
> I just tried it in mobile view and it looks good. What do you think?
> 
> ![Capture d’écran 2021-05-30 à 11 54 31](https://user-images.githubusercontent.com/4655583/120066034-d6f43500-c074-11eb-8d3a-9c76a23439bf.png)
> 

nice!
