### ISSUE TITLE
Cannot install with Flarum 1.0.0

### ISSUE THREAD

**Issue by hschneider66** [AntoineFr/flarum-ext-online#32]
Trying to install throws the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires antoinefr/flarum-ext-online ^0.5.0 -> satisfiable by antoinefr/flarum-ext-online[v0.5.0].
    - antoinefr/flarum-ext-online v0.5.0 requires flarum/core >=0.1.0-beta.16 <=0.1.0 -> found flarum/core[v0.1.0-beta.16] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by AntoineFr** [comment]
Hello,

I just tagged a new release, you should be able to install this extension on Flarum 1.0 !

**Comment by hschneider66** [comment]
Thanks. It can be installed now, but it crashes when I activate it in the backend. The whole backend is blocked and the browser console shows this error:

TypeError: null is not an object (evaluating 't.type')
Globaler Code — admin:94

**Comment by AntoineFr** [comment]
Did you run the command `php flarum cache:clear` to clear the cache after installing this extension ?

**Comment by AntoineFr** [comment]
Oh I found a problem when trying to replicate your issue, I will tag a new version soon.

**EDIT** : It's now fixed, can you update this extension and try again?
```
composer require antoinefr/flarum-ext-online
php flarum cache:clear
```

**Comment by hschneider66** [comment]
Yes, I cleared the cache. Same effect after trying again with your update.
I can send you a Docker image of Flarum 1.0.0, if you want.

**Comment by AntoineFr** [comment]
Can you try to disable all the other extensions you have enabled (and clear the cache again) to be sure it's related to my extension?

I just installed a blank Flarum 1.0 and I didn't encounter this error.

Also do you have more lines in the error, or just these 2?

**Comment by hschneider66** [comment]
You're right: I disabled all other plugins, cleared the cache and enabled yours and it works. Thanks for pointing in the right direction!

**Comment by hschneider66** [comment]
I re-enabled all others and everything still works. Looks like some cache problem of the previous issue. You can close this ticket - thank you very much!
